version: "2"
services:
  # app:
  #   container_name: app
  #   restart: always
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mongo
  #     - postgres
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "37017:27017"
  postgres:
    container_name: postgresql
    image: postgres
    ports:
      - "6432:5432"
volumes:
  mongodata: